# Generated by Django 3.2.12 on 2023-12-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Back', '0003_element_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='acte',
            field=models.TextField(blank=True),
        ),
    ]
